name: Draw keymap
on:
  workflow_dispatch:
  push:
    paths:
      - "kanata.kbd"
      - "keymap-drawer/config.yaml"
      - ".github/workflows/draw.yml"

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install keymap-drawer
        run: pip install keymap-drawer

      - name: Draw Kanata keymap
        run: |
          keymap -c keymap-drawer/config.yaml parse -k kanata.kbd > keymap-drawer/kanata_keymap.yaml
          keymap -c keymap-drawer/config.yaml draw keymap-drawer/kanata_keymap.yaml > img/kanata-keymap.svg

      - name: Commit and push generated SVG
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add keymap-drawer/kanata_keymap.yaml keymap-drawer/kanata_keymap_test.svg
          git commit -m "chore(draw): draw Kanata keymap" || true
          git push
